export enum WdErrorCodes {
  ENDTIME_SAME_OR_BEFORE_STARTTIME,
  TIME_CONFLICT,
  ITEM_DOES_NOT_EXIST,
  TIMESPAN_NOT_FOUND,
  CANNOT_END_PENDING,
  ALREADY_PENDING,
  CANNOT_REMOVE_TIMESPAN,
  CANNOT_ADD_TIMESPAN,
  CANNOT_MERGE
}

